version: '3'

services:
  app:
    build: .
    env_file:
      - '.env'
    depends_on:
      - database
    networks:
      - app-net
  database:
    container_name: pdi_database
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'database_data:/var/lib/postgresql'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=pdi
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  database_data:
    driver: local
